### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by MESWEB** [denetwerkspecialist/Auctions#3]
Blank Page after installation. XAMPP localhost.

**Comment by denetwerkspecialist** [comment]
Please check our new release Community Edition 1.0.
Tomorrow we will release  Community Edition 1.0.1 where we add only dummy content with can be changed by the admin users

**Comment by MESWEB** [comment]
@denetwerkspecialist U call this version CE 1.0? This code is still WeBid 1.2.1 with full of issues and errors like this one - `$NOW = time();` . Serious you keep date as VARCHAR ?? LOL.
``created` varchar(8) NOT NULL default '',
  `lastlogin` varchar(14) NOT NULL default '',`

**Comment by kendellmendoza** [comment]
I agree with @MESWEB . There's lots of room for improvements. For one, what specific versions of PHP/Apache/MySQL are supported? I have tested with various versions with different results each time.

**Comment by denetwerkspecialist** [comment]
@MESWEB Please us what you mean with  There's lots of room for improvements. (send us a list by mail) we fix it ( at the back-end Webid 1.2.1 we also had many errors and it did break all the time.
Our CE version is stable at our hosting but we know we need to fix a lot of things.

**Comment by MESWEB** [comment]
@denetwerkspecialist Make here TODO list and users will update this list.

**Comment by denetwerkspecialist** [comment]
fixed in new release
